### PR TITLE
* Added ITelevisionApi, added Images.Stills property

### PR DESCRIPTION
**Pull request by VPKSoft**
Hi,
I added a first beta for ITelevisionApi as it was "missing".
I also added Images.Stills property.

nuspec file was also updated.

Hopefully this helps further development of the library.
Ps. I tried to maintain your coding style so it sort of would look the same throughout the project..

### CODE REVIEW

**Comment by tonykaralis** [comment]
Hi, 
Thanks for this, I appreciate all the help I can get. 
I will look at this ASAP and get back to you.
Thanks 👍

**Comment by VPKSoft** [comment]
Hi,
Thank you for taking this merge pull request into account.
I'm wondering though as a new user of the GitHub if you choose to accept the merge, can I then delete the fork I made? I wish not to confuse the users by downloading from the "wrong" fork..

**Comment by tonykaralis** [comment]
Hi, Once I have accepted the merge I believe you can still delete the fork. May i ask why you would want to delete your fork though? And when you mention 'users' who are you referring to?

**Comment by VPKSoft** [comment]
Hi,
If there is then left only one branch of the library - then there is only one place to download it from, so no confusion. The users I'm referring to are such as I am, the users of this library - the GPLv3 (or MIT with no dependencies to the new MS License, .NET Core) are actually the only licenses which are compatible with the software I'm building right now, which would be a lightweight HTPC software..

**Comment by tonykaralis** [comment]
Hi this really shouldn't be an issue. On many large open source projects there are 10's or 100's of forks. As long as you reference the correct one then you will getting the code from that repo. If someone chooses to take a look at a fork then that's completely fine. I wont be changing the license on this so you shouldn't have any issues. I must be honest this is the first time I have come across this issue.

**Comment by tonykaralis** [comment]
With your htpc software are you using this library via nuget?

**Comment by tonykaralis** [comment]
Also once I have accepted the merge, would you like me to add your name as a collaborator on the docs? I believe that any help should be recognised.

**Comment by VPKSoft** [comment]
Hi,
Yes I'm using this library via a NuGet and my software is not even in a beta phase so that is why I made a very slim page for it on my website (https://www.vpksoft.net/2-uncategorised/131-vamp) to request an API key from the TMDb.
The software called XBMC, later the Kodi started to get "laggy" as I changed the OS from Linux to Windows (surprise!) due upgrade to a newer version of the Linux Mint distribution and the display chip didn't get along after the upgrade.

**Comment by VPKSoft** [comment]
But okay, I don't delete the fork then 👍

**Comment by tonykaralis** [comment]
Neat, when its ready let me know and Ill give it a try.

**Comment by VPKSoft** [comment]
Great, thank you.

**Comment by tonykaralis** [comment]
I have just pushed the new nuget package. It should be available within a couple hours, just busy indexing.

**Comment by VPKSoft** [comment]
The new nuget package doesn't seem to include the ITelevisionApi..

**Comment by VPKSoft** [comment]
No worries though, I can use the source code with my project..

**Comment by tonykaralis** [comment]
Strange, my master branch has all your code. I will look into this.

**Comment by VPKSoft** [comment]
Perhaps the the compile was made with debug or release witch didn't update the nuget as it was supposed to as the "nuget pack" creates a package with debug version and the "nuget pack -Prop Configuration=Release" makes a nuget from a release version.

**Comment by tonykaralis** [comment]
Yeap i forgot to do that. I will only be able to do that when i get home today. About 6.30pm tp 7pm

**Comment by tonykaralis** [comment]
I have released another version. Set to release mode and used the command you sent me, hope this works.

**Comment by VPKSoft** [comment]
Hi,
Thank you - I'll test this tomorrow.

**Comment by VPKSoft** [comment]
Getting this weird warning though:
"Package 'TMdbEasy 0.3.3' is not found in the following primary source(s): 'https://api.nuget.org/v3/index.json'. Please verify all your online package sources are available (OR) package id, version are specified correctly."

Might be that the indexing isn't completed yet..

**Comment by tonykaralis** [comment]
Yeah I haven't got the Indexing confirmation yet.

**Comment by VPKSoft** [comment]
Hi,
This is now working, thank you. Now to create my own NuGet from this: https://github.com/VPKSoft/TMDbFileUtils..

**Comment by tonykaralis** [comment]
Great, looks good. If you happy with the project and you don't mind starring it 👍

**Pull request merged**
